/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SELF_LEARNING;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NONG HOANG VU
 */
public class QLSVJframe extends javax.swing.JFrame {
        private STUDENT_SERVICE std_sv;
        private DefaultTableModel tblModel;

        public QLSVJframe() {
                // this.std_sv = new STUDENT_SERVICE();
                initComponents();
                addData();
                fillTable();
        }

        public void addData() {
                this.std_sv = new STUDENT_SERVICE();
                this.std_sv.insert(new Student("A", "PH001", "a@fpt.edu.vn", "123abc", 1, 1, "Phát triển phần mềm"));
                this.std_sv.insert(new Student("B", "PH002", "b@fpt.edu.vn", "123abc", 1, 1, "Lập trình game"));
                this.std_sv.insert(new Student("C", "PH003", "c@fpt.edu.vn", "123abc", 1, 0, "Xử lý dữ liệu"));
        }

        public void fillTable() {
                DefaultTableModel tblModel = (DefaultTableModel) tblStudent.getModel();
                tblModel.setRowCount(0);
                this.std_sv = new STUDENT_SERVICE();
                for (Student std : this.std_sv.getList()) {
                        DefaultTableModel tblModel_ = (DefaultTableModel) tblStudent.getModel();
                        String gender = (std.getGender() == 0) ? "Nữ" : "Nam";
                        String status = (std.getStatus() == 0) ? "Stopping" : "Studying";
                        Object[] row = { std.getName(), std.getId(), std.getEmail(), gender, status, std.getMajor() };
                        tblModel_.addRow(row);
                }
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                buttonGroup1 = new javax.swing.ButtonGroup();
                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                txtName = new javax.swing.JTextField();
                txtStudentID = new javax.swing.JTextField();
                txtEmail = new javax.swing.JTextField();
                txtPw = new javax.swing.JPasswordField();
                jLabel5 = new javax.swing.JLabel();
                rdoFemale = new javax.swing.JRadioButton();
                rdoMale = new javax.swing.JRadioButton();
                jLabel6 = new javax.swing.JLabel();
                cbStatus = new javax.swing.JCheckBox();
                jLabel7 = new javax.swing.JLabel();
                cboMajor = new javax.swing.JComboBox<>();
                btnAdd = new javax.swing.JButton();
                btnRemove = new javax.swing.JButton();
                btnChange = new javax.swing.JButton();
                btnClear = new javax.swing.JButton();
                btnExit = new javax.swing.JButton();
                jPanel2 = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                tblStudent = new javax.swing.JTable();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

                jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel1.setText("Họ tên");

                jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel2.setText("Mã SV");

                jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel3.setText("Email");

                jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel4.setText("Mật khẩu");

                jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel5.setText("Giới tính");

                buttonGroup1.add(rdoFemale);
                rdoFemale.setSelected(true);
                rdoFemale.setText("Nữ");

                buttonGroup1.add(rdoMale);
                rdoMale.setText("Nam");

                jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel6.setText("Trạng thái");

                cbStatus.setText("Studying");

                jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel7.setText("Chuyên ngành");

                cboMajor.setModel(new javax.swing.DefaultComboBoxModel<>(
                                new String[] { "Mời chọn", "Lập trình web", "Phát triển phần mềm", "Lập trình mobile",
                                                "Lập trình game", "Xử lý dữ liệu", "Ứng dụng phần mềm" }));

                btnAdd.setText("Thêm");
                btnAdd.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAddActionPerformed(evt);
                        }
                });

                btnRemove.setText("Xóa");
                btnRemove.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                btnRemoveMouseClicked(evt);
                        }
                });

                btnChange.setText("Sửa");
                btnChange.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnChangeActionPerformed(evt);
                        }
                });

                btnClear.setText("Clear");
                btnClear.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnClearActionPerformed(evt);
                        }
                });

                btnExit.setText("Exit");
                btnExit.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnExitActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                false)
                                                                                                                .addComponent(jLabel1,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(jLabel2,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(jLabel3,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(jLabel4,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                false)
                                                                                                                .addComponent(txtStudentID,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                200,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(txtName)
                                                                                                                .addComponent(txtEmail)
                                                                                                                .addComponent(txtPw))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(jLabel5)
                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                .addComponent(rdoFemale)
                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                .addComponent(rdoMale))
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(jLabel6)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                .addComponent(cbStatus))
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(jLabel7)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                .addComponent(cboMajor,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                84,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(btnAdd)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(btnChange)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(btnRemove)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(btnClear)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(btnExit)))
                                                                .addContainerGap(65, Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel1)
                                                                                .addComponent(txtName,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel5)
                                                                                .addComponent(rdoFemale)
                                                                                .addComponent(rdoMale))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel2)
                                                                                .addComponent(txtStudentID,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel6)
                                                                                .addComponent(cbStatus))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel3)
                                                                                .addComponent(txtEmail,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel7)
                                                                                .addComponent(cboMajor,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel4)
                                                                                .addComponent(txtPw,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(btnAdd)
                                                                                .addComponent(btnChange)
                                                                                .addComponent(btnRemove)
                                                                                .addComponent(btnClear)
                                                                                .addComponent(btnExit))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

                tblStudent.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {

                                },
                                new String[] {
                                                "Họ tên", "Mã SV", "Email", "Giới tính", "Trạng thái", "Chuyên ngành"
                                }));
                tblStudent.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tblStudentMouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(tblStudent);

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jScrollPane1)
                                                                .addContainerGap()));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                138,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap()));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jPanel2,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jPanel1,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap()));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnChangeActionPerformed
                DefaultTableModel tblModel = (DefaultTableModel) tblStudent.getModel();
                String name = txtName.getText();
                String id = txtStudentID.getText();
                String email = txtEmail.getText();

                tblModel.setValueAt(name, tblStudent.getSelectedRow(), 0);
                tblModel.setValueAt(id, tblStudent.getSelectedRow(), 1);
                tblModel.setValueAt(email, tblStudent.getSelectedRow(), 2);

                // Show message display
                JOptionPane.showMessageDialog(this, "Update success", "Update", JOptionPane.INFORMATION_MESSAGE);
        }// GEN-LAST:event_btnChangeActionPerformed

        private void tblStudentMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tblStudentMouseClicked
                DefaultTableModel tblModel = (DefaultTableModel) tblStudent.getModel();
                // Set data to text field when raw is selected
                String tblName = tblModel.getValueAt(this.tblStudent.getSelectedRow(), 0).toString();
                String tblId = tblModel.getValueAt(this.tblStudent.getSelectedRow(), 1).toString();
                String tblEmail = tblModel.getValueAt(this.tblStudent.getSelectedRow(), 2).toString();

                // Set to text field
                txtName.setText(tblName);
                txtStudentID.setText(tblId);
                txtEmail.setText(tblEmail);
        }// GEN-LAST:event_tblStudentMouseClicked

        private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnClearActionPerformed
                clear();
        }// GEN-LAST:event_btnClearActionPerformed

        private void btnRemoveMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnRemoveMouseClicked
                DefaultTableModel tblModel = (DefaultTableModel) tblStudent.getModel();
                tblModel.removeRow(this.tblStudent.getSelectedRow());
        }// GEN-LAST:event_btnRemoveMouseClicked

        public void clear() {
                txtName.setText("");
                txtStudentID.setText("");
                txtEmail.setText("");
                txtPw.setText("");
                rdoFemale.setSelected(true);
                cbStatus.setSelected(false);
                cboMajor.setSelectedIndex(0);
        }

        private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddActionPerformed
                // Add row data
                String gender = rdoFemale.isSelected() ? "Nu" : "Nam";
                String status = cbStatus.isSelected() ? "Studying" : "Stopping";
                String selectMajor = (String) cboMajor.getSelectedItem();

                String[] rowData = { txtName.getText(), txtStudentID.getText(), txtEmail.getText(), gender, status,
                                selectMajor };
                DefaultTableModel tblModel = (DefaultTableModel) tblStudent.getModel();
                tblModel.addRow(rowData);
                clear();
        }// GEN-LAST:event_btnAddActionPerformed

        private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnExitActionPerformed
                System.exit(0);
        }// GEN-LAST:event_btnExitActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(QLSVJframe.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(QLSVJframe.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(QLSVJframe.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(QLSVJframe.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new QLSVJframe().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAdd;
        private javax.swing.JButton btnChange;
        private javax.swing.JButton btnClear;
        private javax.swing.JButton btnExit;
        private javax.swing.JButton btnRemove;
        private javax.swing.ButtonGroup buttonGroup1;
        private javax.swing.JCheckBox cbStatus;
        private javax.swing.JComboBox<String> cboMajor;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JRadioButton rdoFemale;
        private javax.swing.JRadioButton rdoMale;
        private javax.swing.JTable tblStudent;
        private javax.swing.JTextField txtEmail;
        private javax.swing.JTextField txtName;
        private javax.swing.JPasswordField txtPw;
        private javax.swing.JTextField txtStudentID;
        // End of variables declaration//GEN-END:variables
}
